version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: base-postgres
    ports:
      - 5432:5432

  app:
    build: .
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
